
Config is: GlobalConfig(image=ImageConfig(image_size=32, patch_size=7, n_channels=1), transformer=TransformerConfig(hidden_dim=128, num_heads=4, num_layers=4, mlp_dim=512, activation_name='GELU', attention_only=True, attn_hidden_layer=True), layernorm=LayerNormConfig(qknorm=False, layer_norm_eps=0.0), dropout=DropoutConfig(patch=0.0, position=0.0, attention=0.0, proj=0.0, mlp=0.0), init=InitializationConfig(weight_type='he', cls_std=1e-06, pos_std=0.02), training=TrainingConfig(loss_fn_name='CrossEntropy', lr=0.001, num_epochs=5, batch_size=64, warmup_steps=0, weight_decay=0.0, device='cuda', seed=0, optimizer_name='AdamW'), logging=LoggingConfig(log_dir='logs', log_frequency=10, print_every=0, use_wandb=True), saving=SavingConfig(parent_dir='/network/scratch/s/sonia.joseph/vit_planetarium', save_dir='checkpoints', save_checkpoints=True, save_cp_frequency=10), classification=<vit_planetarium.configs.CircleConfig.ClassificationConfig object at 0x7fa18cf232d0>)
0it [00:00, ?it/s]                                                                                                                                                                                                                                                              | 0/5 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                                                                           | 0/5 [00:00<?, ?it/s]
E
======================================================================
ERROR: test_train_function (__main__.TestTrainingFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_trainer_circle.py", line 24, in test_train_function
    trained_model = train(self.model, self.config, self.train_dataset, self.val_dataset)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/src/vit_planetarium/training/trainer.py", line 51, in train
    for idx, (images, labels) in tqdm(enumerate(train_loader)):
ValueError: too many values to unpack (expected 2)
----------------------------------------------------------------------
Ran 1 test in 5.315s
FAILED (errors=1)