
Config is: GlobalConfig(image=ImageConfig(image_size=32, patch_size=7, n_channels=1), transformer=TransformerConfig(hidden_dim=128, num_heads=4, num_layers=4, mlp_dim=512, activation_name='GELU', attention_only=False, attn_hidden_layer=True), layernorm=LayerNormConfig(qknorm=False, layer_norm_eps=0.0), dropout=DropoutConfig(patch=0.0, position=0.0, attention=0.0, proj=0.0, mlp=0.0), init=InitializationConfig(weight_type='he', cls_std=1e-06, pos_std=0.02), training=TrainingConfig(loss_fn_name='CrossEntropy', lr=0.0008, num_epochs=100, batch_size=256, warmup_steps=10, weight_decay=0.0, device='cuda', seed=0, optimizer_name='AdamW'), logging=LoggingConfig(log_dir='logs', log_frequency=10, print_every=0, use_wandb=True), saving=SavingConfig(parent_dir='/network/scratch/s/sonia.joseph/vit_planetarium', save_dir='checkpoints', save_checkpoints=True, save_cp_frequency=10), classification=<vit_planetarium.configs.CircleConfig.ClassificationConfig object at 0x7f549400d910>)
E
======================================================================
ERROR: test_train_function (__main__.TestTrainingFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_trainer_circle.py", line 24, in test_train_function
    trained_model = train(self.model, self.config, self.train_dataset, self.val_dataset)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/src/vit_planetarium/training/trainer.py", line 37, in train
    model.to(config.training.device)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
----------------------------------------------------------------------
Ran 1 test in 3.014s
FAILED (errors=1)