
Config is: GlobalConfig(image=ImageConfig(image_size=32, patch_size=7, n_channels=1), transformer=TransformerConfig(hidden_dim=128, num_heads=4, num_layers=4, mlp_dim=512, activation_name='GELU', attention_only=False, attn_hidden_layer=True), layernorm=LayerNormConfig(qknorm=False, layer_norm_eps=0.0), dropout=DropoutConfig(patch=0.0, position=0.0, attention=0.0, proj=0.0, mlp=0.0), init=InitializationConfig(weight_type='he', cls_std=1e-06, pos_std=0.02), training=TrainingConfig(loss_fn_name='CrossEntropy', lr=0.0005, num_epochs=50000, batch_size=-1, warmup_steps=10, weight_decay=0.1, device='cuda', seed=0, optimizer_name='AdamW', scheduler_step=1000, scheduler_gamma=0.5), logging=LoggingConfig(log_dir='logs', log_frequency=30, print_every=0, use_wandb=True), saving=SavingConfig(parent_dir='/network/scratch/s/sonia.joseph/vit_planetarium', save_dir='checkpoints', save_checkpoints=True, save_cp_frequency=10), classification=<vit_planetarium.configs.CircleConfig.ClassificationConfig object at 0x7f8bee88d450>)
E
======================================================================
ERROR: test_train_function (__main__.TestTrainingFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_trainer_circle.py", line 24, in test_train_function
    trained_model = train(self.model, self.config, self.train_dataset, self.val_dataset)
  File "/home/mila/s/sonia.joseph/ViT-Planetarium/src/vit_planetarium/training/trainer.py", line 58, in train
    batch_size_train, batch_size_test = len(train_dataset), len(test_dataset) # use full batch
NameError: name 'test_dataset' is not defined
----------------------------------------------------------------------
Ran 1 test in 6.642s
FAILED (errors=1)